---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: target-group

name: specific

description: 

conditions:
  allOf:
    - property:
        name: number-property
        operator: eq
        operands:
            - 123
