---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag

flag: AI boolean
flagType: boolean
description: created using unify assistants
labels:

availableValues:
  - "true"
  - "false"

isPermanent: false
