---
apiVersion: featuremanagement.cloudbees.io/v1alpha1
kind: flag

flag: fm-test-flag
flagType: boolean
description: test Description
labels:

availableValues:
  - "true"
  - "false"

isPermanent: false
